In [7]:
# Answer 1:

import numpy as np
arr = np.arange(2,50,3)
print(arr)


[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [ ]:
#Answer 2:

import numpy as np
lst1=[] 
lst2=[]for i in range(5):

    n=int(input("Enter elements in list 1: "))
    lst1.append(n)
for i in range(5):
    n=int(input("Enter elements in list 2: "))
    lst2.append(n)
#converting list into numpy array
arr1=np.array(lst1)    
arr2=np.array(lst2)
#Concatenating arrays
arr1=np.concatenate((arr1,arr2))
print(arr1)
#sorting array
arr1=np.sort(arr1)
print("Array after sorting: \n ",arr1)


In [5]:
#Answer 3:

import numpy as np
arr=np.array([[1,3,5],[2,4,6],[3,5,7]])
print(arr)
print("Dimension of array:",arr.ndim)
print("Shape of array:",arr.shape)



[[1 3 5]
 [2 4 6]
 [3 5 7]]
Dimension of array: 2
Shape of array: (3, 3)


In [ ]:
#Answer 4:

import numpy as np
arr=np.arange(10)
print("\nShape of Array :",arr.shape)

# converting using newaxis in row wise
row_arr = arr[np.newaxis, :]
print("\nShape of 2d Array in row major :",row_arr.shape)

# converting using newaxis in column wise
col_arr = arr[:, np.newaxis]
print("\nShape of 2d Array in column major :",col_arr.shape)



In [9]:
#Answer 5:

import numpy as np
arr1=np.square([1,2,3,4,5])
arr2=np.square([6,7,8,9,10])
print("Vertical stack:\n",np.vstack((arr1,arr2)))
print("Horizontal stack:\n",np.hstack((arr1,arr2)))

Vertical stack:
 [[  1   4   9  16  25]
 [ 36  49  64  81 100]]
Horizontal stack:
 [  1   4   9  16  25  36  49  64  81 100]


In [4]:
#Answer 6:

import numpy as np
number_list = np.array([1, 1, 2, 3, 4, 4, 1,5,6,7,5,4,5,6,5,7,])

(unique, counts) = np.unique(number_list, return_counts=True)
frequencies = np.asarray((unique, counts)).T

print(frequencies)

[[1 3]
 [2 1]
 [3 1]
 [4 3]
 [5 4]
 [6 2]
 [7 2]]
